version: "3"

services:
  proxy:
    container_name: traefik
    image: traefik
    networks:
      - traefik
    ports:
      - 80:80
      - 8080:8080
      - 443:443
    volumes:
      - "$PWD/traefik.toml:/etc/traefik/traefik.toml"
      - "$PWD/acme:/etc/traefik/acme"
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    labels:
      - "traefik.frontend.rule=Host:traefik-ovh2.synker.ovh"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.entryPoints=http,https"

  rancher:
    container_name: rancher
    image: rancher/server
    networks:
      - traefik
    ports:
      - 8080:8080
    volumes:
      - .:/var/lib/mysql
    restart: unless-stopped
    
networks:
  traefik:
    external: true