version: "3"

services:
  elasticsearch:
    image: elasticsearch:latest
    container_name: elasticsearch
    command:
      - elasticsearch
      - -Des.node.name=elasticsearch
      - -Des.node.master=false
      - -Des.node.data=false
      - -Des.discovery.zen.ping.unicast.hosts=master01,master02
      - -Des.network.host=_eth0_
    ports:
      - "9200:9200"
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - elknet
  data01:
    container_name: data01
    image: elasticsearch:latest
    command:
      - elasticsearch
      - -Des.node.name=data01
      - -Des.node.master=false
      - -Des.discovery.zen.ping.unicast.hosts=master01,master02
      - -Des.network.host=_eth0_
    ports:
      - "9201:9200"
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - elknet
  data02:
    container_name: data02
    image: elasticsearch:latest
    command:
      - elasticsearch
      - -Des.node.name=data02
      - -Des.node.master=false
      - -Des.discovery.zen.ping.unicast.hosts=master01,master02
      - -Des.network.host=_eth0_
    ports:
      - "9202:9200"
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      placement:
        constraints: [node.role == worker]
    networks:
      - elknet
  master01:
    container_name: master01
    image: elasticsearch:latest
    command:
      - elasticsearch
      - -Des.node.name=master01
      - -Des.node.data=false
      - -Des.node.client=false
      - -Des.discovery.zen.ping.unicast.hosts=master02
      - -Des.discovery.zen.minimum_master_nodes=2
      - -Des.network.host=_eth0_
    ports:
      - "9210:9200"
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - elknet
  master02:
    container_name: master02
    image: elasticsearch:latest
    command:
      - elasticsearch
      - -Des.node.name=master02
      - -Des.node.data=false
      - -Des.node.client=false
      - -Des.discovery.zen.ping.unicast.hosts=master01
      - -Des.discovery.zen.minimum_master_nodes=2
      - -Des.network.host=_eth0_
    ports:
      - "9211:9200"
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - elknet
  kibana:
    image: kibana:latest
    container_name: kibana
    command: kibana --elasticsearch 'http://elasticsearch:9200'
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    deploy:
      placement:
        constraints: [node.role == worker]
    networks:
      - elknet
  dockerbeat:
    container_name: dockerbeat
    build: ingensi/dockerbeat
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    depends_on:
      - elasticsearch
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - elknet
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8090:8090"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - elknet
networks:
  elknet: