version: "3.4"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:${TAG}
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.zen.minimum_master_nodes=1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - node.name=elasticsearch
    ulimits:
      memlock: -1
      nofile:
        hard: 65536
        soft: 65536
      nproc: 65538
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    deploy:
      mode: replicated
      replicas: 1
      endpoint_mode: dnsrr
      placement:
        constraints: 
          - node.labels.size == large
  kibana:
    image: kibana:${TAG}
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == worker
          - node.labels.size == medium
    healthcheck:
      test: wget -qO- http://localhost:5601 > /dev/null
      interval: 30s
      retries: 3
    volumes:
      - kibana:/usr/share/kibana/data

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    ports:
      - "12201:12201/udp"
    configs: # https://docs.docker.com/compose/compose-file/#long-syntax
      - source: ls_config
        target: /usr/share/logstash/pipeline/logstash.conf
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: 
          - node.labels.provider == ovh

  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    # disable strict permission checks
    command: ["--strict.perms=false"]
    #command: -e -E 'output.elasticsearch.password=${ELASTIC_PASSWORD}'
    volumes:
      - filebeat_webgrab_sitepack:/mnt/log:ro
      - filebeat:/usr/share/filebeat/data
      - /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      - /var/lib/docker/containers/:/var/lib/docker/containers/:ro

      # # This is needed for filebeat to load jenkins build log path as specified in filebeat.yml
      # - /var/lib/docker/volumes/jenkins_home/_data/jobs/:/var/lib/docker/volumes/jenkins_home/_data/jobs/:ro

      # This is needed for filebeat to load logs for system and auth modules
      - /var/log/:/var/log/:ro
      # This is needed for filebeat to load logs for auditd module
      # - /var/log/audit/:/var/log/audit/:ro
    # disable strict permission checks
    command: ["--strict.perms=false"]
    configs:
     - source: fb_config
       target: /usr/share/filebeat/filebeat.yml
    user: root
    networks:
      - elk
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
          - node.hostname == master
    depends_on: 
        - elasticsearch
        - logstash

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: 
          - node.role == worker
          - node.labels.size == small

networks:
  elk:
    driver: overlay
    driver_opts:
      encrypted: "true"

volumes:
  elasticsearch:
  kibana:
  filebeat_webgrab_sitepack:
    driver_opts:
      type: "nfs"
      o: "rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,local_lock=none,no_root_squash,addr=18.194.42.216"
      device: ":/webgrab_volume/config/siteini.pack"

configs:
  fb_config:
    file: filebeat.yml