version: "3.3"

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-platinum:${TAG}
    environment:
      - ES_JAVA_OPTS=-Xms2g -Xmx2g
      - discovery.zen.minimum_master_nodes=1
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - node.name=elasticsearch
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - elk-2
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 20m
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.labels.size == large

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    networks:
      - elk-2
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: 
          - node.role == worker
          - node.labels.size == medium
    # healthcheck:
    #   test: wget -qO- http://kibana:5601 > /dev/null
    #   interval: 20m
    #   retries: 3
    volumes:
      - kibana_data:/usr/share/kibana/data

  logstash:
    image: docker.elastic.co/logstash/logstash:${TAG}
    # configs: # https://docs.docker.com/compose/compose-file/#long-syntax
    #   - source: ls_config
    #     target: /usr/share/logstash/config/logstash.yml
    #     mode: 0440
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:${ELASTICSEARCH_PORT}
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    #   - 'xpack.monitoring.elasticsearch.password=${ELASTIC_PASSWORD}'
    #   - 'xpack.monitoring.elasticsearch.username=${ELASTICSEARCH_USERNAME}'
    #   - 'xpack.monitoring.elasticsearch.url="http://elasticsearch:9200"'
    #   - 'path.config="/usr/share/logstash/config"'
    ports:
      - "12201:12201/udp"
      - "9600:9600"
    networks:
      - elk-2
    volumes:
      - logstash_config:/usr/share/logstash/config
      - logstash_pipeline:/usr/share/logstash/pipeline
      - logstash_data:/var/lib/logstash
      - logstash_log:/var/log/logstash
    deploy:
      mode: replicated
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 3m
        max_attempts: 3
        window: 120s
      placement:
        constraints: 
          - node.labels.provider == ovh
    depends_on: 
        - elasticsearch

  filebeat:
    image: docker.elastic.co/beats/filebeat:${TAG}
    # disable strict permission checks
    command: ["--strict.perms=false"]
    volumes:
      - filebeat_webgrab_sitepack:/usr/share/sitepack/:ro
      #- /var/run/docker.sock:/var/run/docker.sock
      # This is needed for filebeat to load container log path as specified in filebeat.yml
      #- /var/lib/docker/containers/:/var/lib/docker/containers/:ro

      # # This is needed for filebeat to load jenkins build log path as specified in filebeat.yml
      # - /var/lib/docker/volumes/jenkins_home/_data/jobs/:/var/lib/docker/volumes/jenkins_home/_data/jobs/:ro

      # This is needed for filebeat to load logs for system and auth modules
      #- /var/log/:/var/log/:ro
      # This is needed for filebeat to load logs for auditd module
      # - /var/log/audit/:/var/log/audit/:ro
    # disable strict permission checks
    configs:
     - source: fb_config
       target: /usr/share/filebeat/filebeat.yml
    networks:
      - elk-2
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5m
        max_attempts: 3
        window: 120s
      placement:
        constraints:
          - node.role == worker
          - node.hostname == gcp-1
    depends_on: 
        - elasticsearch
        - logstash

  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: 
          - node.role == manager
          - node.labels.size == small

networks:
  elk-2:
    driver: overlay
    driver_opts:
      encrypted: "true"

volumes:
  elasticsearch_data:
     driver_opts:
      type: "nfs"
      #o: "rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,nolock,soft,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,local_lock=none,no_root_squash,addr=18.194.42.216"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/elastic/data"
  kibana_data:
     driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/kibana/data"
  filebeat_webgrab_sitepack:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/config/siteini.pack"
  filebeat_data:
    driver_opts:
      type: "nfs"
      o: "addr=18.194.42.216,nolock,soft,rw"
      device: ":/webgrab_volume/filebeat/data"
  logstash_config:
    driver_opts:
      type: "nfs"
      o: "addr=18.194.42.216,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/config"
  logstash_pipeline:
    driver_opts:
      type: "nfs"
      o: "addr=18.194.42.216,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/pipeline"
  logstash_data:
    driver_opts:
      type: "nfs"
      o: "addr=18.194.42.216,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/data"
  logstash_log:
    driver_opts:
      type: "nfs"
      o: "addr=18.194.42.216,nolock,soft,rw"
      device: ":/webgrab_volume/logstash/log"

configs:
  fb_config:
    file: filebeat.yml
  ls_config:
    file: $PWD/logstash/config/logstash.yml