version: "3"

services:
  consul_server:
    image: progrium/consul
    container_name: consul
    restart: always
    ports:
      - 8500:8500
      - 8301:8301
      - 8300:8300
      - 8600:53
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "server":true, "enable_debug":true, \"disable_update_check\": true}'
      - CONSUL_CLIENT_INTERFACE=_eth0_
      - CONSUL_BIND_INTERFACE=_eth0_
    command: -server -bootstrap -ui-dir /ui
    volumes:
      - .:/consul/data
  consul_agent_1:
    image: progrium/consul
    container_name: consul_agent1
    depends_on:
      - consul_server
    restart: always
    ports:
      - 8401:8400
      - 8311:8301
      - 8310:8300
      - 8501:8500
      - 8601:8600
    environment:
      - CONSUL_BIND_INTERFACE=_eth0_
    command: -server -ui-dir /ui join=consul_server
    volumes:
      - .:/consul/data
  consul_agent_2:
    image: progrium/consul
    container_name: consul_agent2
    depends_on:
      - consul_server
    restart: always
    ports:
      - 8402:8400
      - 8312:8301
      - 8313:8300
      - 8502:8500
      - 8602:8600
    environment:
      - CONSUL_BIND_INTERFACE=_eth0_
    command: -server -ui-dir /ui join=consul_server
    volumes:
      - .:/cSonsul/data
  registrator:
    image: gliderlabs/registrator:master
    container_name: registrator
    depends_on:
      - consul_server
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"
    command: -internal consul://consul:8500