version: "3"

services:
  consul:
    image: progrium/consul
    container_name: consul
    restart: always
    ports:
      - 8500:8500
      - 8301:8301
      - 8300:8300
    environment:
      - 'CONSUL_LOCAL_CONFIG={"skip_leave_on_interrupt": true, "server":true, "enable_debug":true}'
      - CONSUL_CLIENT_INTERFACE=_eth0_
      - CONSUL_BIND_INTERFACE=_eth0_
    command: 
    command: -server -bootstrap -ui-dir /ui
    volumes:
      - .:/consul/data
