version: "3"

services:
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
    networks:
      - overlayNet
    deploy:
      placement:
        constraints: [node.role == manager]
 
  db:
    image: postgres:9.4
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - overlayNet
    deploy:
      placement:
        constraints: [node.role == manager]
 
  voting-app:
    image: gaiadocker/example-voting-app-vote:good
    ports:
      - 5000:80
    networks:
      - overlayNet
    depends_on:
      - redis
    deploy:
      mode: replicated
      replicas: 2
      labels: [APP=VOTING]
      placement:
        constraints: [node.role == worker]
 
  result-app:
    image: gaiadocker/example-voting-app-result:latest
    ports:
      - 5001:80
    networks:
      - overlayNet
    depends_on:
      - db
 
  visualizer:
    container_name: visu
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      -  overlayNet
networks:
  overlayNet:
volumes:
  db-data:
