version: "3.3"

services:

  webgrab:
    image: linuxserver/webgrabplus
    environment:
      - PGID=0 
      - PUID=0
    volumes:
      - type: bind
        source: ./config
        target: /config
      - type: bind
        source: ./data
        target: /data
    deploy:
      placement:
        constraints: 
          - node.role == worker
          - node.labels.size == small