version: "3.3"

services:

  webgrab:
    image: linuxserver/webgrabplus
    environment:
      - PGID=1001 
      - PUID=1001
    volumes:
      - "./config:/config"
      - "./data:/data"
    deploy:
      placement:
        constraints: 
          - node.role == worker
          - node.labels.size == small