version: "3.3"

services:

  webgrab:
    image: linuxserver/webgrabplus
    environment:
      - PGID=0 
      - PUID=0
    volumes:
      - type: bind
        source: config
        target: /config

      - type: bind
        source: data
        target: /data
    deploy:
      placement:
        constraints: 
          - node.role == worker
          - node.labels.size == small
volumes:
  config:
    driver_opts:
      type: "nfs4"
      o: "rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,local_lock=none,addr=ovh1"
      device: ":/webgrab_volume/config"
  data:
    driver_opts:
      type: "nfs4"
      o: "rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,local_lock=none,addr=ovh1"
      device: ":/webgrab_volume/data"