version: "3.3"

services:

  webgrab:
    image: linuxserver/webgrabplus
    environment:
      - PGID=0
      - PUID=0
    volumes:
      - "config:/config"
      - "data:/data"
    deploy:
      placement:
        constraints: 
          - node.role == worker
          - node.hostname == synker.machine.arub1
          
volumes:
  config:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/webgrab/config"
  data:
    driver_opts:
      type: "nfs"
      o: "nolock,soft,rw,addr=18.194.42.216"
      device: ":/webgrab_volume/webgrab/data"